/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Cfx Studio. All rights reserved.
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

/**
 * Pure-data + lookup helpers for the FiveM natives reference.
 * Loaded from shared/natives-data/natives.json (generated by
 * ide/build/fetch-natives.mjs).
 */

export interface NativeParam {
	name: string;
	type: string;
	description?: string;
}

export interface NativeDef {
	name: string;
	hash: string;
	ns: string;
	params: NativeParam[];
	results: string;
	description?: string;
	apiset?: string;
	aliases?: string[];
}

export interface NativesIndex {
	natives: NativeDef[];
	fetchedAt: number;
}

export function indexByName(idx: NativesIndex): Map<string, NativeDef> {
	const m = new Map<string, NativeDef>();
	for (const n of idx.natives) { m.set(n.name, n); }
	return m;
}

export function indexByNamespace(idx: NativesIndex): Map<string, NativeDef[]> {
	const m = new Map<string, NativeDef[]>();
	for (const n of idx.natives) {
		const arr = m.get(n.ns) ?? [];
		arr.push(n);
		m.set(n.ns, arr);
	}
	return m;
}

export function searchNatives(idx: NativesIndex, q: string, limit = 100): NativeDef[] {
	const needle = q.trim().toLowerCase();
	if (!needle) { return idx.natives.slice(0, limit); }
	const out: NativeDef[] = [];
	for (const n of idx.natives) {
		if (n.name.toLowerCase().includes(needle) || n.ns.toLowerCase().includes(needle)) {
			out.push(n);
			if (out.length >= limit) { break; }
		}
	}
	return out;
}

/**
 * For environments (Node, webview) that need to load the JSON synchronously
 * from a known location. Returns null when the file isn't reachable; the
 * caller is expected to fall back to a different source.
 */
export async function loadNativesFromUrl(url: string): Promise<NativesIndex | null> {
	try {
		const res = await fetch(url);
		if (!res.ok) { return null; }
		const data = await res.json();
		if (!data || !Array.isArray((data as Partial<NativesIndex>).natives)) { return null; }
		return data as NativesIndex;
	} catch {
		return null;
	}
}
